# Simple workflow for deploying static content to GitHub Pages
name: Execute doxygen & upload to gh-pages

on:
  # Runs on pushes and merges, preferably only main project branch "testat-007"
  push:
    branches: [ "main" ]
              #[ "feature_gh_pages_doxygen" ] #for testing and validation only

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # Setup for deployment, installing applications
    steps:
      - name: Install doxygen
        run: sudo apt install -y doxygen graphviz

      - name: Checkout
        uses: actions/checkout@v3
      
      # executing predefined Doxyfile
      - name: create Doxygen output
        run: doxygen Doxyfile
      
      - name: create top-level index.html
        run: echo \<meta http-equiv=\""Refresh\"" content=\""0; url='https://github.com/cndrw/2P-Tetris-Arduino/html/index.html'\"" /\>  > doxygen_output/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{github.workspace}}/doxygen_output'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1